### ISSUE TITLE
未收藏任何条目加载出错时显示的信息

### ISSUE THREAD

**Issue by yaqinking** [MainasuK/Bangumi-M#4]
现在显示的「请求超时」其实是因为「还没有任何收藏」
~~小号首次登录时发现的……~~
![](http://i.imgur.com/6iPeyBJl.jpg)

**Comment by MainasuK** [comment]
了解，发现这个是因为刚刚开始学 Swift 时候，太嫩了，所以才犯的错……
未收藏时返回值为 null。

不过后来写函数都有考虑超时和失败的区别，虽然只是个样子（更底层的请求并不能返回超时和失败的区别
嗯，开了新分支，周末抽时间修修

**Comment by MainasuK** [comment]
修复计划暂时搁置，没研究透新语法怎么处理闭包的错误抛出，Swift 更加完善后去修吧……

**Comment by yaqinking** [comment]
了解 
~~先暂时关闭 w~~

**Comment by MainasuK** [comment]
Fixed.
