### ISSUE TITLE
关于主页条目排序的问题

### ISSUE THREAD

**Issue by yaqinking** [MainasuK/Bangumi-M#8]
能否提供一个选项为：点格子后将条目移动到最下面显示

也就是：未点格子的在最上面，而不是现在刚点的格子，刷新一下后，刚点的在最上面。（新 ep 未上映的话，显示在最上面也不能点……）转移到列表最下面（或者暴力直接反转数组数据，不过那样的话下面的就没意义了……）

我觉得理想情况下使用这个应用的流程是：
1. 打开应用
2. 显示条目
   1. 可选任一：默认顶部显示昨天上映的动画（过去 24 小时内，在上个版本中有「周几再来吧」的话，那这个应该可以处理的吧……）
   2. 可选任一：默认顶部显示今天将要上映的动画 （从现在起 24 小时内） 
3. 在首屏幕基本不用滑动，或者滑动一个屏幕的高度就可以把需要点的格子搞定。（因为自己基本上都是在看昨天晚上，或者今天上映的番组。）

当然，番组 ep 全部都上映完毕的话，那点单个格子后的排序位置还是默认的，刷新后在最顶部就 ok，毕竟是在补番中，点完一个 ep 后，过 20 多分钟就要点下一个。

大致如此。（可以考虑下。）

**Comment by MainasuK** [comment]
目前 API 返回的数据是按照最近标记的顺序排列的，这个功能也是某一次 API 更新了才有。条目信息里包含了 timestamp，可以利用它来按日期排序，效果和 onAir 一样。

至于你提的这个，利用 Model 里现有的数据是可以做一个 sorter，大概是一个计算型变量～先留着考虑吧，因为现在得先搞定这几个 beta 的 BUG。万一时间不够，到了开学的时候我就只能把 API 给你自己做啦。

**Comment by yaqinking** [comment]
了解。（不过窝要是参与的话也是在工具链都正式 release 之后了，最近也在做其它的东西 w）

**Comment by MainasuK** [comment]
@yaqinking 尝试着去实现了一下，结果发现了不少问题……代码是这样的

```
            let today = Date()
            let calendar = Calendar(identifier: .gregorian)

            guard let cstTimeZone = TimeZone(abbreviation: "CST"),
            let weekdayInt = calendar.dateComponents(in: cstTimeZone, from: today).weekday,
            let weekday = WeekOfBGMDay(rawValue: weekdayInt)?.toBGMDay() else {
                return subjects
            }

            var tempSubjects = Subjects()

            tempSubjects.append(contentsOf: subjects.filter { $0.airWeekday == weekday } )
            tempSubjects.append(contentsOf: subjects.filter { ($0.airWeekday - 1) % 7 == weekday } )
            tempSubjects.append(contentsOf: subjects.filter { ($0.airWeekday + 1) % 7 == weekday } )

            let uniqueSubjectIDs = tempSubjects.map { $0.id }
            tempSubjects.append(contentsOf: subjects.filter { !uniqueSubjectIDs.contains($0.id) } )

            return tempSubjects
```

大体上就是一个计算型变量 (computed variable)，按照今日放送，昨日放送，明日放送以及其他的顺序对现有条目进行重排列。但是结果和 onAir 不同，代码是没问题的（大概？），问题出在 API 返回的结果中不包含放送信息，也就不知道该条目还是不是在播出，或有没有完结。

如你所见，这个版本的进度管理将条目进度和条目之间的关系分离开了，条目进度的获取是在得到用户收藏列表之后（每次刷新之后有个 spinner 就是由于这个原因）。这个问题也好解决，修改回原来的逻辑就可以了😔……

---

在不改动代码逻辑的情况下，恐怕只能做个动漫和三次元的排序了，残念～

**Comment by yaqinking** [comment]
嗯，对窝来说只要有动画这个分类就满足需求了……
~~这 filter 一下 map 一下看的我是一脸萌比 =_=~~

**Comment by MainasuK** [comment]
@yaqinking 如果 API 返回的结果包含在读漫画、小说什么的，加个分类还有点用，不过现在的情况……大概没人会在意吧😄

暂时关闭这个 issue 了，不过如果你有兴趣做一个延时 enable 的分类按钮也不是不行～

**Comment by yaqinking** [comment]
~~嗯，本身就是一个奇怪的需求w~~

**Comment by MainasuK** [comment]
@yaqinking 还好吧，平常追新番的话还蛮有用。只可惜 API 不是自己的，想加什么功能都得抓网页，哪个爬虫大牛接了这个锅我就轻松多了😉
